### Criar um novo post
POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "Novo Post",
  "content": "Conteúdo do novo post"
}

### Obter todos os posts
GET http://localhost:3000/posts

### Apagar um post
DELETE http://localhost:3000/posts/1

### Adicionar um comentário a um post
POST http://localhost:3000/posts/1/comments
Content-Type: application/json

{
  "content": "Novo comentário no post"
}

### Apagar um comentário de um post
DELETE http://localhost:3000/posts/8/comments/1